### ISSUE TITLE
Shader Compatibility

### ISSUE THREAD

**Issue by jjc54** [feldim2425/MoreOverlays#6] opened 2016-04-14 02:02 UTC
None of the overlay features work when any shader packs are being used. Tested with Sildur/MrMeeps. Not sure if you need anything from me but just let me know if you do.

**Comment by feldim2425** [comment] 2016-04-14 16:37
Can you please tell me the Forge version, MC version and the Shader Mod / Optifine Version?

**Comment by jjc54** [comment] 2016-04-14 23:39
Minecraft: 1.9
Forge: forge-12.16.0.1859
Shader mod has been incorporated into Optifine: preview_OptiFine_1.9.0_HD_U_B2_pre
(You will find that here: http://optifine.net/downloads.php under the preview section at the top)
Shaders: MrMeepz Shaders v05 Ultra Motionblur
(http://tinyurl.com/pbaa7uy)

**Comment by feldim2425** [comment] 2016-04-15 04:51
I will try but I don't think that there is a way to fix this. I think the Optifine version is not a Forgeversion and it is closed source. Probably Optifine messes up Forge.

**Comment by jjc54** [comment] 2016-04-15 04:53
Oh ok I'll switch to a forge version once optifine updates to the latest forge. Thanks

**Comment by jriwanek** [comment] 2016-04-15 05:41
The preview version of optifine gets updated sometimes without the filename changing, currently (as of 04/13/2016) it's been rebased against 1863, @feldim2425 Not sure where you got the idea it's not a forge compatible, it has been since the late A? Releases, official "stable" for 1.9 is also forge compatible but with 1797.

**Comment by jriwanek** [comment] 2016-04-15 05:43
See changelog:
http://www.optifine.net/changelog?f=preview_OptiFine_1.9.0_HD_U_B2_pre.jar
(07.04.2016)

Also see the date under "preview versions":
http://www.optifine.net/downloads
(13.04.2016)

**Comment by feldim2425** [comment] 2016-04-15 13:33
@jriwanek It didn't worked in the dev-environment. I will try it in a normal Minecraft instance. I hope it works. I'm not a huge fan of OptiFine. Last time I used it was in MC 1.6.4

**Comment by feldim2425** [comment] 2016-04-15 20:18
Ok I looked why it doesn't work.
Screenshot (It is very dark and it doesn't render from every angle):
![2016-04-15_22 12 30](https://cloud.githubusercontent.com/assets/6705744/14573795/80b96578-0357-11e6-8aaa-d40eaf0ecdd9.png)

But I found this on the forum post for MrMeepz Shaders v05 in the Download section:
" _This Shaderpack is optimized for Minecraft 1.7, the result in 1.8 is too dark and washed out and looks by far not as good as in 1.7. If you want to get the best result, use Minecraft 1.7 instead._ "

EDIT: You can also see that on the blocks in the village on the screenshot
I will try some other shaders if something similar happens.

**Comment by jriwanek** [comment] 2016-04-16 00:34
The problem is that Optifine disables the Forge Rendering pipeline, I think a fix in progress, but I suspect it'll take a while to get done, hopefully somehow optifine's rendering pipeline can be jimmied onto Forge's and everything can be made to work together properly. I doubt however this can be considered a bug in More Overlays though.

**Comment by jjc54** [comment] 2016-04-16 22:43
Ah okay, I have already made an issue about Optifine's forge rendering pipeline and it is being worked on. Not sure if it will be fixed in 1.9 since Optifine is now 1.9.2, but the problem is known.

By the way, I know MrMeepz is "optimized for 1.7" but I did say that I used several other packs, with none allowing More Overlays to work.

**Comment by feldim2425** [comment] 2016-04-17 18:55
Optifine is closed source so I can't look whats messing up the tessellator.
Even if it is open source it will be to much code to check where the problem is.
I tried some stuff like enabling GLBlend, ... and it doesn't change anything.
Also I didn't found any code in Vanilla MC or on GitHub that can bypass shaders.

If the bug is only in More Overlays it should also appear in "Vanilla" MC and if a part of the bug is in this Mod I don't know what I have to change.

If anyone has an idea how to fix this bug, please make a Pull Request or write a comment in this Issue.

**Comment by feldim2425** [comment] 2016-07-04 10:30
I still work on a fix. I fixed at least the invisible lines. But there are still some bugs.

![2016-07-04_12 26 44](https://cloud.githubusercontent.com/assets/6705744/16557942/e472f650-41e2-11e6-9d88-44b6f7b3cc79.png)

EDIT: I will do some other stuff from my todo-list and hopefully I can upload a new version soon.

**Comment by feldim2425** [comment] 2016-07-04 21:42
Ok I uploaded a version (1.5) that should fix at least the invisible lines (at least in some packs) but I will not close this because they are still a bit bugy (like in the screenshot in my last comment)

**Comment by feldim2425** [comment] 2018-07-23 15:30
I will close this one.
The borders show up (at least) and even Vanilla chunk lines are buggy with shaders. So I will say this is a issue that optifine has to fix. I don't see why other mods have to fix it when shaders break into the rendering pipeline.

**Closed as completed by feldim2425** 2018-07-23 15:30 UTC
Labels: help wanted, incompatibility issue
