### ISSUE TITLE
Double click to search is wonky with tinkers construct crafting station

### ISSUE THREAD

**Issue by ShaunDreclin** [feldim2425/MoreOverlays#22] opened 2017-02-25 07:09 UTC
Only a small area of the search box is clickable/highlighted for searching See screenshot:

![screenshot 589](https://cloud.githubusercontent.com/assets/5851433/23329138/76962888-faff-11e6-913c-8513559e0efe.png)

Works fine in inventory/normal crafting bench

Edit: When search bar is on the right it's actually too big, though that's much less annoying than too small. See second screenshot:

![screenshot 593](https://cloud.githubusercontent.com/assets/5851433/23329148/ac25a1b8-faff-11e6-97ce-51d5a9160571.png)

**Comment by feldim2425** [comment] 2017-02-26 21:22
Have you resized the minecraft window while the GUI was open?

**Comment by ShaunDreclin** [comment] 2017-02-27 00:21
Nope I just set the window size when I launch the game.

**Comment by feldim2425** [comment] 2017-03-07 11:14
I tried but I can't reproduce this bug. If anyone knows how I can reproduce this.

**Comment by ShaunDreclin** [comment] 2017-03-07 11:57
You're doing it on the tinkers construct crafting table right? It doesnt happen on normal crafting tables.
You could try it in the All The Mods: Expert pack, maybe theres some other mod causing a conflict of some sort.

Its really not a huge issue though if you don't want to hassle with it! ^^;

**Comment by feldim2425** [comment] 2017-03-07 21:23
Ok I will try the Modpack. Hopefully I can reproduce the bug ^^

**Comment by feldim2425** [comment] 2019-08-29 02:01
Since I where never really able to reproduce the bug and the version is probably outdated anyway I will close this issue. Feel free to open a new one if the issue persists in newer versions.

**Closed as completed by feldim2425** 2019-08-29 02:01 UTC
Labels: Bug, Can't reproduce
