### ISSUE TITLE
Yellow item search bar overlay too long

### ISSUE THREAD

**Issue by ghost** [feldim2425/MoreOverlays#40] opened 2017-12-01 05:28 UTC
![more overlays item search bug](https://user-images.githubusercontent.com/25916106/33469067-c5bc8b2c-d660-11e7-974f-c83a0f4f2a30.png)

**Minecraft version**: 1.12.2
**Forge version**: 12.18.3.2511
**More Overlays version**: 1.11
**Just Enough Items version**: 3.14.7.420

**Comment by feldim2425** [comment] 2017-12-01 06:24
Tinkers Table? If thats the case it is a duplicate of #22

**Comment by ghost** [comment] 2017-12-01 07:22
Nope. It happens in any inventory.

**Comment by feldim2425** [comment] 2019-06-13 22:12
I will close this an  merge it with #22

**Closed as completed by feldim2425** 2019-06-13 22:12 UTC
Labels: Bug, Can't reproduce
